"""Build PDF figures for the UDA-lite section of the course paper.

Generates two figures saved into ``paper/``:

* ``uda_lite_progression.pdf`` -- DINOv2-Small mIoU on ACDC validation across
  the source-only baseline E3, the offline pseudo-label run U1 and the online
  EMA + ClassMix run U2.
* ``pseudo_label_keep_ratio.pdf`` -- per-condition statistics of confidence
  filtered pseudo-labels generated by the U1 teacher on ACDC train.

The script is self-contained: numbers come from the evaluation notebooks and
from the U1 pseudo-label generation notebook, so no extra data files are
required.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

PAPER_DIR = Path(__file__).resolve().parents[1] / "paper"
PAPER_DIR.mkdir(parents=True, exist_ok=True)

# ---- DINOv2-Small evaluation metrics (overall + per-condition mIoU) --------
# Values match notebooks/eval/acdc/{e3,u1,u2}/DinoV2_*_ACDC_Evaluation.ipynb.
STAGES = ["E3", "U1", "U2"]
OVERALL = np.array([0.5711, 0.5828, 0.5957])
CONDITIONS = ["fog", "night", "rain", "snow"]
PER_CONDITION = {
    "fog":   np.array([0.6977, 0.7001, 0.7055]),
    "night": np.array([0.3823, 0.3887, 0.3980]),
    "rain":  np.array([0.5542, 0.5898, 0.6058]),
    "snow":  np.array([0.6004, 0.5977, 0.6087]),
}

# ---- U1 pseudo-label statistics on ACDC train -----------------------------
# Values from notebooks/pseudo/acdc/u1/DinoV2_U1_ACDC_Train_PseudoLabel_Generation.ipynb.
KEEP_RATIO = {
    "fog":   0.8297,
    "night": 0.6543,
    "rain":  0.8018,
    "snow":  0.7933,
}
CONFIDENCE_KEPT = {
    "fog":   0.9920,
    "night": 0.9871,
    "rain":  0.9906,
    "snow":  0.9897,
}


def _style() -> None:
    plt.rcParams.update({
        "font.family": "DejaVu Serif",
        "font.size": 10,
        "axes.titlesize": 11,
        "axes.labelsize": 10,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.linestyle": "--",
        "grid.alpha": 0.4,
        "legend.frameon": False,
    })


def build_progression() -> Path:
    """Two-panel chart: overall mIoU progression and per-condition mIoU."""

    _style()
    fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.2))
    overall_ax, cond_ax = axes

    # --- left panel: overall mIoU as connected points -----------------------
    overall_ax.plot(
        STAGES,
        OVERALL,
        marker="o",
        markersize=7,
        linewidth=2.0,
        color="#1f4e79",
    )
    for x, y in zip(STAGES, OVERALL):
        overall_ax.annotate(
            f"{y:.4f}",
            xy=(x, y),
            xytext=(0, 10),
            textcoords="offset points",
            ha="center",
            fontsize=9,
        )
    overall_ax.set_title("Overall mIoU на ACDC validation")
    overall_ax.set_xlabel("Этап")
    overall_ax.set_ylabel("mIoU")
    overall_ax.set_ylim(0.55, 0.61)

    # --- right panel: per-condition grouped bars ----------------------------
    # Wider per-group spacing keeps neighbouring value labels apart.
    x = np.arange(len(CONDITIONS)) * 1.5
    width = 0.36
    palette = ["#a4c2d6", "#5b8db5", "#1f4e79"]
    for i, stage in enumerate(STAGES):
        values = [PER_CONDITION[c][i] for c in CONDITIONS]
        bars = cond_ax.bar(
            x + (i - 1) * width,
            values,
            width,
            label=stage,
            color=palette[i],
            edgecolor="white",
            linewidth=0.5,
        )
        # Vertical labels inside the bars avoid overlapping with neighbours.
        for bar, vi in zip(bars, values):
            text_color = "white" if i == 2 else "#1a1a1a"
            cond_ax.text(
                bar.get_x() + bar.get_width() / 2,
                vi - 0.015,
                f"{vi:.3f}",
                ha="center",
                va="top",
                rotation=90,
                fontsize=8,
                color=text_color,
            )
    cond_ax.set_xticks(x)
    cond_ax.set_xticklabels(CONDITIONS)
    cond_ax.set_ylim(0.30, 0.80)
    cond_ax.set_title("mIoU по погодным условиям")
    cond_ax.set_xlabel("Условие")
    cond_ax.set_ylabel("mIoU")
    cond_ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.18),
        ncols=3,
        fontsize=9,
    )

    fig.tight_layout()
    out = PAPER_DIR / "uda_lite_progression.pdf"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    return out


def build_keep_ratio() -> Path:
    """Bar chart of pseudo-label keep ratio and confidence per condition."""

    _style()
    fig, ax = plt.subplots(figsize=(8.0, 3.8))

    conds = list(KEEP_RATIO.keys())
    keep = np.array([KEEP_RATIO[c] for c in conds])
    conf = np.array([CONFIDENCE_KEPT[c] for c in conds])

    x = np.arange(len(conds))
    width = 0.38

    bars_keep = ax.bar(
        x - width / 2,
        keep,
        width,
        label="Keep ratio",
        color="#1f4e79",
        edgecolor="white",
        linewidth=0.5,
    )
    bars_conf = ax.bar(
        x + width / 2,
        conf,
        width,
        label="Confidence (kept)",
        color="#a4c2d6",
        edgecolor="white",
        linewidth=0.5,
    )

    for bars, values in ((bars_keep, keep), (bars_conf, conf)):
        for bar, v in zip(bars, values):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                v + 0.012,
                f"{v:.3f}",
                ha="center",
                va="bottom",
                fontsize=9,
            )

    ax.set_xticks(x)
    ax.set_xticklabels(conds)
    ax.set_ylim(0.0, 1.10)
    ax.set_xlabel("Условие ACDC")
    ax.set_ylabel("Доля")
    ax.set_title("U1: фильтрация pseudo-labels на ACDC train, $\\tau=0.90$")
    # Place legend outside the data area to avoid overlap with the snow bars.
    ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.18),
        ncols=2,
        fontsize=9,
    )

    fig.tight_layout()
    out = PAPER_DIR / "pseudo_label_keep_ratio.pdf"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    return out


if __name__ == "__main__":
    p1 = build_progression()
    p2 = build_keep_ratio()
    print(f"saved: {p1}")
    print(f"saved: {p2}")
